version: '3.7'

services:

  sample:
    container_name: container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/src'
      - '/src/node_modules'
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
